name: bioinformatics-files
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - picard=2.26.3
    - bwa=0.7.17
    - samtools
    - crumble=0.8.3
    - parallel-fastq-dump=0.6.7
